### ISSUE TITLE
Error in schema definition

### ISSUE THREAD

**Issue by mjordan** [mjordan/islandora_repository_reports#75]
islandora_repository_reports/blob/main/config/schema/islandora_repository_reports.schema.yml should be:

```
# Schema for the configuration files of the Islandora Repository Reports module.
islandora_repository_reports.settings:
  type: config_object
  label: 'Islandora Repository Reports admin settings'
  mapping:
    islandora_repository_reports_randomize_pie_chart_colors:
      type: boolean
      label: 'Randomize colors in pie charts'
    islandora_repository_reports_cache_report_data:
      type: boolean
      label: 'Cache report data'
    islandora_repository_reports_bar_chart_color:
      type: string
      label: 'Bar color'
```
and correspondingly https://raw.githubusercontent.com/mjordan/islandora_repository_reports/main/config/install/islandora_repository_reports.settings.yml should be:

```
islandora_repository_reports_randomize_pie_chart_colors: TRUE
islandora_repository_reports_pie_or_doughnut: 'pie'
islandora_repository_reports_cache_report_data: FALSE
islandora_repository_reports_bar_chart_color: '#0080ff'
```
